name: GPS
version: '${project.version}'
main: fr.sixpixels.gps.GPS
api-version: '1.20'
softdepend: [Citizens]

commands:
  gps:
    description: Permet de choisir une destination
    usage: /<command> [add | delete | list | reload]

permissions:
  gps.use:
    description: Allow player to use the GPS
    default: true
  gps.admin:
    description: Allow player to add and remove destinations
    default: op